version: "3.8"
services:
  rathole-server:
    image: rapiz1/rathole:latest
    container_name: rathole-server
    restart: unless-stopped
    ports:
      - "2333:2333/tcp"
      - "3889:3389/tcp"
      - "3889:3389/udp"
    volumes:
      - ./server.toml:/etc/rathole/server.toml:ro
      - /var/log/rathole:/var/log
    command: ["rathole", "-c", "/etc/rathole/server.toml"]
