[server]
bind_addr = "0.0.0.0:2333"

[server.services.rdp_tcp]
type = "tcp"
bind_addr = "0.0.0.0:3389"
token = "token"

[server.services.rdp_udp]
type = "udp"
bind_addr = "0.0.0.0:3389"
token = "token"