[server]
bind_addr = "0.0.0.0:2333"

log_file = "/var/log/rathole/server.log"
log_level = "info"

[server.services.rdp_tcp]
bind_addr = "0.0.0.0:3389"

# [server.services.rdp_udp]
# bind_addr = "0.0.0.0:3389"
# protocol = "udp"
