server_addr = "40.160.5.97"
server_port = 7000
token = "X8u#4qPz7!vA9LmR2$yT6eG0bNfZ1hS"

[[proxies]]
name = "rdp_tcp"
type = "tcp"
local_addr = "127.0.0.1:3389"
remote_port = 3389

[[proxies]]
name = "rdp_udp"
type = "udp"
local_addr = "127.0.0.1:3389"
remote_port = 3389