[common]
server_addr = "40.160.5.97"
server_port = 7000

[rdp]
type = "tcp"
local_ip = "127.0.0.1"
local_port = 3389
remote_port = 3389

[rdp_udp]
type = "udp"
local_ip = "127.0.0.1"
local_port = 3389
remote_port = "3389"